<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKMI1ZCQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKMI1ZCQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKMI1ZCQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKMI1ZCQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKMI1ZCQ\App_KernelProdContainer([
    'container.build_hash' => 'KMI1ZCQ',
    'container.build_id' => 'bbdc4004',
    'container.build_time' => 1740672396,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKMI1ZCQ');
