<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxeww2D\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxeww2D/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSxeww2D.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSxeww2D\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSxeww2D\App_KernelProdContainer([
    'container.build_hash' => 'Sxeww2D',
    'container.build_id' => '4527038e',
    'container.build_time' => 1770240958,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxeww2D');
