<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'alx_home' => [[], ['_controller' => 'App\\Controller\\DefaultController::home'], [], [['text', '/']], [], [], []],
    'alx_christmas_card' => [[], ['_controller' => 'App\\Controller\\DefaultController::merryChristmas'], [], [['text', '/merry-christmas']], [], [], []],
    'alx_about' => [[], ['_controller' => 'App\\Controller\\DefaultController::about'], [], [['text', '/about']], [], [], []],
    'alx_portfolio' => [[], ['_controller' => 'App\\Controller\\DefaultController::portfolio'], [], [['text', '/portfolio_2']], [], [], []],
    'alx_action_plan' => [[], ['_controller' => 'App\\Controller\\DefaultController::actionPlan'], [], [['text', '/actionPlan']], [], [], []],
    'alx_todo' => [[], ['_controller' => 'App\\Controller\\DefaultController::todo'], [], [['text', '/todo']], [], [], []],
    'app_web_evolution' => [[], ['_controller' => 'App\\Controller\\DefaultController::webEvolution'], [], [['text', '/web-evolution']], [], [], []],
    'app_portfolio_index' => [[], ['_controller' => 'App\\Controller\\PortfolioController::index'], [], [['text', '/portfolio/']], [], [], []],
    'app_portfolio_new' => [[], ['_controller' => 'App\\Controller\\PortfolioController::new'], [], [['text', '/portfolio/new']], [], [], []],
    'app_portfolio_show' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'app_portfolio_edit' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'app_portfolio_delete' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'App\Controller\DefaultController::home' => [[], ['_controller' => 'App\\Controller\\DefaultController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\DefaultController::merryChristmas' => [[], ['_controller' => 'App\\Controller\\DefaultController::merryChristmas'], [], [['text', '/merry-christmas']], [], [], []],
    'App\Controller\DefaultController::about' => [[], ['_controller' => 'App\\Controller\\DefaultController::about'], [], [['text', '/about']], [], [], []],
    'App\Controller\DefaultController::portfolio' => [[], ['_controller' => 'App\\Controller\\DefaultController::portfolio'], [], [['text', '/portfolio_2']], [], [], []],
    'App\Controller\DefaultController::actionPlan' => [[], ['_controller' => 'App\\Controller\\DefaultController::actionPlan'], [], [['text', '/actionPlan']], [], [], []],
    'App\Controller\DefaultController::todo' => [[], ['_controller' => 'App\\Controller\\DefaultController::todo'], [], [['text', '/todo']], [], [], []],
    'App\Controller\DefaultController::webEvolution' => [[], ['_controller' => 'App\\Controller\\DefaultController::webEvolution'], [], [['text', '/web-evolution']], [], [], []],
    'App\Controller\PortfolioController::index' => [[], ['_controller' => 'App\\Controller\\PortfolioController::index'], [], [['text', '/portfolio/']], [], [], []],
    'App\Controller\PortfolioController::new' => [[], ['_controller' => 'App\\Controller\\PortfolioController::new'], [], [['text', '/portfolio/new']], [], [], []],
    'App\Controller\PortfolioController::show' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'App\Controller\PortfolioController::edit' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
    'App\Controller\PortfolioController::delete' => [['id'], ['_controller' => 'App\\Controller\\PortfolioController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/portfolio']], [], [], []],
];
