services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  app.portfolio_uploader:
    class: AdminBundle\FileUploader
    arguments: ['%portfolio_directory%']
  app.doctrine_portfolio_listener:
        class: AdminBundle\EventListener\PortfolioUploadListener
        arguments: ['@app.portfolio_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }