<?php

namespace AppBundle\Repository;

/**
 * PortfolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioRepository extends \Doctrine\ORM\EntityRepository
{
}
