app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    schemes:  ['%httpProtocol%']
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    schemes:  ['%httpProtocol%']