<?php

namespace AdminBundle\Repository;

/**
 * PortofolioImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortofolioImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
