<?php

namespace AdminBundle\Repository;

/**
 * PortfolioImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortfolioImagesRepository extends \Doctrine\ORM\EntityRepository
{
  
}
