<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcl1mhL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcl1mhL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcl1mhL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcl1mhL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcl1mhL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bcl1mhL',
    'container.build_id' => '2e66b44a',
    'container.build_time' => 1770207055,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcl1mhL');
