<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_21FsSQ6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.21FsSQ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.21FsSQ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'portfolioRepository' => ['privates', 'App\\Repository\\PortfolioRepository', 'getPortfolioRepositoryService', true],
        ], [
            'portfolioRepository' => 'App\\Repository\\PortfolioRepository',
        ]);
    }
}
