<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CUJBdEsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.CUJBdEs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CUJBdEs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'portfolio' => ['privates', '.errored..service_locator.CUJBdEs.App\\Entity\\Portfolio', NULL, 'Cannot autowire service ".service_locator.CUJBdEs": it needs an instance of "App\\Entity\\Portfolio" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'portfolio' => 'App\\Entity\\Portfolio',
        ]);
    }
}
