<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PortfolioController::delete' => ['privates', '.service_locator.CUJBdEs', 'get_ServiceLocator_CUJBdEsService', true],
            'App\\Controller\\PortfolioController::edit' => ['privates', '.service_locator.CUJBdEs', 'get_ServiceLocator_CUJBdEsService', true],
            'App\\Controller\\PortfolioController::index' => ['privates', '.service_locator.21FsSQ6', 'get_ServiceLocator_21FsSQ6Service', true],
            'App\\Controller\\PortfolioController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PortfolioController::show' => ['privates', '.service_locator.fauiKKc', 'get_ServiceLocator_FauiKKcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PortfolioController:delete' => ['privates', '.service_locator.CUJBdEs', 'get_ServiceLocator_CUJBdEsService', true],
            'App\\Controller\\PortfolioController:edit' => ['privates', '.service_locator.CUJBdEs', 'get_ServiceLocator_CUJBdEsService', true],
            'App\\Controller\\PortfolioController:index' => ['privates', '.service_locator.21FsSQ6', 'get_ServiceLocator_21FsSQ6Service', true],
            'App\\Controller\\PortfolioController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PortfolioController:show' => ['privates', '.service_locator.fauiKKc', 'get_ServiceLocator_FauiKKcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PortfolioController::delete' => '?',
            'App\\Controller\\PortfolioController::edit' => '?',
            'App\\Controller\\PortfolioController::index' => '?',
            'App\\Controller\\PortfolioController::new' => '?',
            'App\\Controller\\PortfolioController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PortfolioController:delete' => '?',
            'App\\Controller\\PortfolioController:edit' => '?',
            'App\\Controller\\PortfolioController:index' => '?',
            'App\\Controller\\PortfolioController:new' => '?',
            'App\\Controller\\PortfolioController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
