<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortfolioRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PortfolioRepository' shared autowired service.
     *
     * @return \App\Repository\PortfolioRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PortfolioRepository'] = new \App\Repository\PortfolioRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
