<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortfolioTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PortfolioType' shared autowired service.
     *
     * @return \App\Form\PortfolioType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PortfolioType'] = new \App\Form\PortfolioType();
    }
}
