<?php

namespace ContainerKMI1ZCQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortfolio2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.fauiKKc.App\Entity\Portfolio' shared service.
     *
     * @return \App\Entity\Portfolio
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fauiKKc": it needs an instance of "App\\Entity\\Portfolio" but this type has been excluded in "config/services.yaml".');
    }
}
